name: publish-to-server
on:
  push:
    branches:
      - curation
      - devel
  workflow_dispatch:

jobs:
  generate-map:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install remotemaker
        run: |
          python -m pip install ${{ vars.REMOTE_MAKER_WHEEL }}
      - name: run remotemaker
        run: |
          commit=${{ github.ref_name }}
          if [[ "curation" == "${{ github.ref_name }}" ]]; then
            server=${{ vars.CURATION_MAP_SERVER }}
            token=${{ secrets.CURATION_SERVER_TOKEN }}
          elif [[ "devel" == "${{ github.ref_name }}" ]]; then
            server=${{ vars.DEVEL_MAP_SERVER }}
            token=${{ secrets.DEVEL_SERVER_TOKEN }}
          fi
          server=${{ vars.CURATION_MAP_SERVER }} 
          python -m remotemaker \
                 --server $server \
                 --token $token \
                 --source ${{ github.server_url }}/${{ github.repository }} \
                 --manifest manifest.json \
                 --commit $commit
