name: restrict-file-changes

on:
  pull_request:
    branches:
      - release

jobs:
  restrict:
    runs-on: ubuntu-latest
    if: github.repository == 'AnatomicMaps/vagus-nerve-flatmap'

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for diffing against base

      - name: Get changed files
        id: changed
        run: |
          echo "files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install minimatch

      - name: Restrict changed files to allowed paths
        env:
          CHANGED: ${{ steps.changed.outputs.files }}
        run: |
          node <<'EOF'
          const minimatch = require('minimatch');
          const changed = process.env.CHANGED.split(/\s+/);
          const allowed = ["description.json", "manifest.json", "properties.json", "vagus.svg"];

          const disallowed = changed.filter(file =>
            !allowed.some(pattern => minimatch.minimatch(file, pattern))
          );

          if (disallowed.length > 0) {
            console.error("❌ Disallowed files detected:");
            disallowed.forEach(f => f ? console.error(`  - ${f}`) : '');
            process.exit(1);
          }

          console.log("✅ All changed files are within allowed paths.");
          EOF

